version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 861276097496.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build API Gateway service...
      - docker build -f apps/api-gateway/Dockerfile -t gwaipro/api-gateway . 
      - docker tag gwaipro/api-gateway:latest 861276097496.dkr.ecr.us-east-1.amazonaws.com/gwaipro/api-gateway:latest

      - echo Build Booking service...
      - docker build -f apps/booking-service/Dockerfile -t gwaipro/booking-service . 
      - docker tag gwaipro/booking-service:latest 861276097496.dkr.ecr.us-east-1.amazonaws.com/gwaipro/booking-service:latest

      - echo Build Payment service...
      - docker build -f apps/payment-service/Dockerfile -t gwaipro/payment-service . 
      - docker tag gwaipro/payment-service:latest 861276097496.dkr.ecr.us-east-1.amazonaws.com/gwaipro/payment-service:latest

      - echo Build Users service...
      - docker build -f apps/users-service/Dockerfile -t gwaipro/users-service . 
      - docker tag gwaipro/users-service:latest 861276097496.dkr.ecr.us-east-1.amazonaws.com/gwaipro/users-service:latest

      - echo Build Chat service...
      - docker build -f apps/chat-service/Dockerfile -t gwaipro/chat-service . 
      - docker tag gwaipro/chat-service:latest 861276097496.dkr.ecr.us-east-1.amazonaws.com/gwaipro/chat-service:latest
      

  post_build:
    commands:
      - echo Pushing images to Amazon ECR...
      - docker push 861276097496.dkr.ecr.us-east-1.amazonaws.com/gwaipro/api-gateway:latest
      - docker push 861276097496.dkr.ecr.us-east-1.amazonaws.com/gwaipro/booking-service:latest
      - docker push 861276097496.dkr.ecr.us-east-1.amazonaws.com/gwaipro/payment-service:latest
      - docker push 861276097496.dkr.ecr.us-east-1.amazonaws.com/gwaipro/users-service:latest
      - docker push 861276097496.dkr.ecr.us-east-1.amazonaws.com/gwaipro/chat-service:latest
