version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - yarn install
  pre_build:
    commands:
      - echo Running pre-build scripts...
      # - yarn build
  build:
    commands:
      - echo Building Docker image...
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <account-id>.dkr.ecr.us-east-1.amazonaws.com)
      - docker build -t gwaipro-microservices:${CODEBUILD_RESOLVED_SOURCE_VERSION} .
      - docker tag gwaipro-microservices:${CODEBUILD_RESOLVED_SOURCE_VERSION} <account-id>.dkr.ecr.us-east-1.amazonaws.com/gwaipro-microservices:${CODEBUILD_RESOLVED_SOURCE_VERSION}
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push <account-id>.dkr.ecr.us-east-1.amazonaws.com/gwaipro-microservices:${CODEBUILD_RESOLVED_SOURCE_VERSION}
artifacts:
  files:
    - '**/*'
