services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
      args:
        - APP_NAME=api-gateway
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - JWT_TOKEN=XcJwVOuNBIngYy06oNgfjBmtVnD3trLw
      - JWT_TOKEN_AUDIENCE=user-service:3003
      - JWT_TOKEN_ISSUER=user-service:3003
      - JWT_ACCESS_TOKEN_TTL=36000
      - JWT_REFRESH_TOKEN_TTL=86400
      - RABBITMQ_URL=amqp://rabbitmq:5672
    volumes:        
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./node_modules:/usr/src/app/node_modules
      - ./apps/api-gateway:/usr/src/app/apps/api-gateway
    depends_on:
      - rabbitmq
      - users-service
      - booking-service
      - payment-service
    command: yarn start:dev api-gateway

  booking-service:
    build:
      context: .
      dockerfile: ./apps/booking-service/Dockerfile
      target: development
      args:
        - APP_NAME=booking-service
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=bookings-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookings
      - RABBITMQ_URL=amqp://rabbitmq:5672
    volumes:        
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./node_modules:/usr/src/app/node_modules
      - ./apps/booking-service:/usr/src/app/apps/booking-service
    depends_on:
      - bookings-db
      - rabbitmq
    command: yarn start:dev booking-service

  payment-service:
    build:
      context: .
      dockerfile: ./apps/payment-service/Dockerfile
      target: development
      args:
        - APP_NAME=payment-service
    ports:
      - 3002:3002
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=payments-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payments
      - RABBITMQ_URL=amqp://rabbitmq:5672
    volumes:        
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./node_modules:/usr/src/app/node_modules
      - ./apps/payment-service:/usr/src/app/apps/payment-service
    depends_on:
      - payments-db
      - rabbitmq
    command: yarn start:dev payment-service

  users-service:
    build:
      context: .
      dockerfile: ./apps/users-service/Dockerfile
      target: development
      args:
        - APP_NAME=users-service
    ports:
      - 3003:3003
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=users-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
      - JWT_SECRET=XcJwVOuNBIngYy06oNgfjBmtVnD3trLw
      - JWT_TOKEN_AUDIENCE=user-service:3003
      - JWT_TOKEN_ISSUER=user-service:3003
      - JWT_ACCESS_TOKEN_TTL=3600
      - JWT_REFRESH_TOKEN_TTL=86400
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - GOOGLE_CLIENT_ID=google-client-id
      - GOOGLE_CLIENT_SECRET=google-client-secret
      - TWILIO_ACCOUNT_SID=twilio-account-sid
      - TWILIO_AUTH_TOKEN=twilio-auth-token
    volumes:        
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./node_modules:/usr/src/app/node_modules
      - ./apps/users-service:/usr/src/app/apps/users-service
    depends_on:
      - users-db
      - redis
      - rabbitmq
    command: yarn start:dev users-service

  chat-service:
    build:
      context: .
      dockerfile: ./apps/chat-service/Dockerfile
      target: development
      args:
        - APP_NAME=chat-service
    ports:
      - 3004:3004
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=chat-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chats
    volumes:        
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./node_modules:/usr/src/app/node_modules
      - ./apps/chat-service:/usr/src/app/apps/chat-service
    depends_on:
      - chat-db
      - rabbitmq
    command: yarn start:dev chat-service

  bookings-db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookings
      - POSTGRES_HOST_AUTH_METHOD=trust

  payments-db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payments
      - POSTGRES_HOST_AUTH_METHOD=trust

  users-db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
      - POSTGRES_HOST_AUTH_METHOD=trust
  
  chat-db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chats
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
