# users-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
      - name: users-service
        image: 992382773921.dkr.ecr.us-east-1.amazonaws.com/gwai-pro/users-service:latest
        ports:
        - containerPort: 3003
        env:
        - name: NODE_ENV
          value: "production"
        - name: POSTGRES_HOST
          value: "users-db.default.svc.cluster.local"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "gwaipro"
        - name: POSTGRES_PASSWORD
          value: "pass123"
        - name: POSTGRES_DB
          value: "users"
        - name: REDIS_HOST
          value: "redis.default.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: RABBITMQ_URL
          value: "amqp://gwaipro:pass123@rabbitmq.default.svc.cluster.local:5672"
        - name: JWT_SECRET
          value: "XcJwVOuNBIngYy06oNgfjBmtVnD3trLw"
        - name: JWT_TOKEN_AUDIENCE
          value: "user-service:3003"
        - name: JWT_TOKEN_ISSUER
          value: "user-service:3003"
        - name: JWT_ACCESS_TOKEN_TTL
          value: "3600"
        - name: JWT_REFRESH_TOKEN_TTL
          value: "86400"
        - name: GOOGLE_CLIENT_ID
          value: "google-client-id"
        - name: GOOGLE_CLIENT_SECRET
          value: "google-client-secret"
        - name: TWILIO_ACCOUNT_SID
          value: "twilio-account-sid"
        - name: TWILIO_AUTH_TOKEN
          value: "twilio-auth-token"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: users-service
# spec:
#   selector:
#     app: users-service
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 3003
#   type: ClusterIP
