apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: 992382773921.dkr.ecr.us-east-1.amazonaws.com/gwai-pro/api-gateway:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: JWT_TOKEN
              value: XcJwVOuNBIngYy06oNgfjBmtVnD3trLw
            - name: JWT_TOKEN_AUDIENCE
              value: user-service:3003
            - name: JWT_TOKEN_ISSUER
              value: user-service:3003
            - name: JWT_ACCESS_TOKEN_TTL
              value: "3600"
            - name: JWT_REFRESH_TOKEN_TTL
              value: "86400"
            - name: RABBITMQ_URL
              value: amqp://rabbitmq:rabbitmq@gwaipro-rabbitmq:5672
      imagePullSecrets:
        - name: ecr-reg