apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: 992382773921.dkr.ecr.us-east-1.amazonaws.com/gwai-pro/api-gateway
          ports:
            - containerPort: 3000
          env:
            - name: RABBITMQ_URL
              value: amqp://rabbitmq:5672
