apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: 992382773921.dkr.ecr.us-east-1.amazonaws.com/gwai-pro/users-service
          ports:
            - containerPort: 3003
          env:
            - name: POSTGRES_HOST
              value: "users-db"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "users"
            - name: JWT_SECRET
              value: "XcJwVOuNBIngYy06oNgfjBmtVnD3trLw"
            - name: JWT_TOKEN_AUDIENCE
              value: "user-service:3003"
            - name: JWT_TOKEN_ISSUER
              value: "user-service:3003"
            - name: JWT_ACCESS_TOKEN_TTL
              value: "3600"
            - name: JWT_REFRESH_TOKEN_TTL
              value: "86400"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
            - name: GOOGLE_CLIENT_ID
              value: "google-client-id"
            - name: GOOGLE_CLIENT_SECRET
              value: "google-client-secret"
            - name: TWILIO_ACCOUNT_SID
              value: "twilio-account-sid"
            - name: TWILIO_AUTH_TOKEN
              value: "twilio-auth-token"
